### ISSUE TITLE
Test for agent death is being performed every cycle

### ISSUE THREAD

**Issue by andre-senna** [petroniocandido/COVID19_AgentBasedSimulation#1]
Probabilities are supposed to represent the probability of the agent die during the whole period of the disease.

https://github.com/petroniocandido/COVID19_AgentBasedSimulation/blob/486fe8552d702a6a7d4587a0298c30e3246eb419/covid_abs/abs.py#L137

**Comment by andre-senna** [comment]
Nervermind. It seems like the probabilities have been calibrated to reflect a daily probability. Sorry to bother you.

**Comment by petroniocandido** [comment]
Don't worry! Feel free to ask anything and give contributions.
